import type { Question } from './types'

export const QUESTIONS: Question[] = [
  { id: 'q-1', conceptLabel: 'maternal-inheritance', segmentId: 'seg-bio4-04', question: 'What is unique about mitochondrial DNA inheritance?', answer: 'It is inherited exclusively from the maternal line. The sperm\'s mitochondria are destroyed after fertilization.', difficulty: 'medium' },
  { id: 'q-2', conceptLabel: 'maternal-inheritance', segmentId: 'seg-bio4-05', question: 'What happens to paternal mitochondria after fertilization?', answer: 'They are tagged for destruction and eliminated from the embryo.', difficulty: 'easy' },
  { id: 'q-3', conceptLabel: 'mito-diseases', segmentId: 'seg-bio4-08', question: 'Why are mitochondrial mutations particularly persistent?', answer: 'There is no recombination in mitochondrial DNA, so harmful mutations cannot be diluted by mixing with healthy copies.', difficulty: 'hard' },
  { id: 'q-4', conceptLabel: 'mito-diseases', segmentId: 'seg-bio4-09', question: 'Name two mitochondrial diseases.', answer: "Leber's hereditary optic neuropathy and MELAS syndrome.", difficulty: 'medium' },
  { id: 'q-5', conceptLabel: 'endosymbiosis', segmentId: 'seg-bio4-02', question: 'What evidence supports the endosymbiotic theory of mitochondria?', answer: 'Mitochondria have their own circular DNA, similar to bacteria, their own ribosomes, a double membrane, and replicate by binary fission.', difficulty: 'medium' },
  { id: 'q-6', conceptLabel: 'cell-respiration', segmentId: 'seg-bio3-05', question: 'What is the net ATP yield from one glucose molecule in cellular respiration?', answer: 'Approximately 30-32 ATP molecules through glycolysis, the citric acid cycle, and oxidative phosphorylation.', difficulty: 'hard' },
  { id: 'q-7', conceptLabel: 'cell-cycle', segmentId: 'seg-bio2-07', question: 'What are the main cell cycle checkpoints?', answer: 'G1 checkpoint (restriction point), G2 checkpoint (before mitosis), and the spindle assembly checkpoint (during mitosis).', difficulty: 'medium' },
  { id: 'q-8', conceptLabel: 'organic-rxns', segmentId: 'seg-chem1-04', question: 'What is the key difference between SN1 and SN2 reactions?', answer: 'SN1 is a two-step mechanism with a carbocation intermediate; SN2 is a one-step concerted mechanism with backside attack.', difficulty: 'hard' },
  { id: 'q-9', conceptLabel: 'cell-membrane', segmentId: 'seg-bio1-02', question: 'Describe the structure of the cell membrane.', answer: 'A phospholipid bilayer with hydrophilic heads facing outward and hydrophobic tails facing inward, with embedded transport proteins.', difficulty: 'easy' },
  { id: 'q-10', conceptLabel: 'mitosis', segmentId: 'seg-bio2-05', question: 'What are the four stages of mitosis?', answer: 'Prophase, metaphase, anaphase, and telophase.', difficulty: 'easy' },
  { id: 'q-11', conceptLabel: 'chemiosmosis', segmentId: 'seg-bio3-07', question: 'How does ATP synthase generate ATP?', answer: 'The proton gradient created by the electron transport chain drives protons back through ATP synthase, which acts like a turbine to produce ATP.', difficulty: 'medium' },
  { id: 'q-12', conceptLabel: 'molecular-clock', segmentId: 'seg-bio4-07', question: 'How is mitochondrial DNA used as a molecular clock?', answer: 'Mitochondrial mutations accumulate at a different rate than nuclear mutations, providing a measurable timeline for evolutionary studies.', difficulty: 'hard' },
  { id: 'q-13', conceptLabel: 'elimination-rxns', segmentId: 'seg-chem1-07', question: "What is Zaitsev's rule?", answer: 'In elimination reactions, the more substituted (more stable) alkene is the major product.', difficulty: 'medium' },
  { id: 'q-14', conceptLabel: 'meiosis', segmentId: 'seg-bio2-10', question: 'How does crossing over contribute to genetic diversity?', answer: 'During meiosis I, homologous chromosomes exchange genetic material, creating new combinations of alleles not found in either parent.', difficulty: 'medium' },
  { id: 'q-15', conceptLabel: 'paternal-mito', segmentId: 'seg-bio4-10', question: 'Is paternal mitochondrial inheritance possible?', answer: 'The consensus is that maternal inheritance is the rule. Rare reported cases may involve heteroplasmy rather than true paternal contribution.', difficulty: 'hard' },
]
